---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAu/zn7r3dkL0VmiZWbxdFJKGLzhdCFHz5vpCJ7rPcYgAo5TGl1ZFCRyRaulFFXbG/PZd9aY85TpMsBrWA63QigfUF4RPwhgcJRQG2xIcFit4JpMVp42XN0oGY3lLsEd0BthNykBH8+vwJDKaMnQrS0UQr/iEkZamPVJR24I6mtCoDtM/vEoZvgtsdcIALFmkpxuCt/R6y1bwfI+BUr5so0nf+oGB2t70THVhsO7Jd6oEMzgTmU1++OsQBaIG36gXCmUzbbeinY6N9lg8VH5IT2SdNrikPq67pp0KB7Vm6yMRJFXSmj0f+hEudqc5kZPdHi2JU/SuOYXq1fXMO1k2yyPLP1y6KhI3UN7EUFKEA0hbCovzU+BApIA7G26eToB6tqiCrnmqnOjBcZMlh6+dLWAu+Y7JkZ9pFOCcKlUq+uZ47Tn4BRvA8xCEqKLZuc39RUU8gvG/mATidIqdt50SI7OKOn7m3Xcx5Y84f8uUOn+sCQtO/dy+wDeSNBO9Fxkc5tniaH3741txCgJTf2wToOrRUa3SWf7bxJL3xUOJZby4hmVNIIzNdssLPZI5nqmVXmS4V9uyLoBpT8eHKL8B2MPGTBEfIg0xBKjAxgxXQ28gQk9n4Jfo2m074hiP5dIgDi6e0l5hdPotEKl0KKfTeVqiCT2ntyng36lI8OAUiEdroK2d/C2iDDQSQgsur7cleqgzslVcy6xgP3lZ3A7GGNY5hFUqJ5xDOvG7k0+2tDxe+ZRrXMZrSp
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
