---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBx0S7mazdFl0/yzm+kfV9A4hOfr/rFk6w5Vn/ZUyNt2qHG6LmN5Z0B6+NzIy+Wk8boEsy1UpB/Mu7WLuFAIH/+zHRGfvsdcCixjcMPVm2cBUyeFWTHlmiUsLNoUyrZRO4w+p0bsGmjqU19fCdRYc0K/4SKm95nau9Y0aZATyIdDSXUBxP6Mw0KpK9DLaeMoJdYdocl0Gr8Gh//DGgYMir75dI/jxdEDSozotH/t9FW4aK6qxMX5NqsW9CoLJVNlPh6TC0h8TZTCEUS+/Lr8ofThUFH19Sg7V/cjjZH3id/KBRpcfiiJJfg53Miom4K2+QRIl9i6XnzXiLq4UkpmDgaxHgJO4XadANmWCWMqHI9uS7UXAfmIX0UFtQBqBKOHvAIG6L3WO34owikOZJiU9p4OlotKjnfJQMTEi5JjxRH3JiMnbRv87uuSKBk+VW5bx69UtZnYlZK3DUUUO5EzSr/eEEoY/il3b7a6WYLyjJANLcsLmwIMbR9AVCTdFSGyHQhNDejNRe1yXD6VguMzBSrko/FNZuW4PtEjM0DliBHuq/WRSwl8hYBRgXWBYonJorHxt9lWauyFdcRZ2L4oE/UHmUwRE8UaQ+vPYNjJUGKKoMj97DoPm+ExX+bGOXZTclKHoHjEgOJS4w6DpmWwuFk2Ftknr41C3XM3pBslcdmuPHkkh2ZJqJlCslwkaea/U06eXCuVuegJ5rg0oE4bx8y2GxAgM07AGljYEYRJgpzLy62k/d4shgc
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
