apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pydio
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pydio.devcw.xyz`)
      kind: Rule
      services:
        - name: pydio-service
          port: 8080
          scheme: https
          serversTransport: pydio-notls
  tls: {}
