---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pydio-secret
  namespace: pydio
spec:
  encryptedData:
    CELLS_DB_PASSWORD: AgB2LlddaWgF+vox57TjQTb65JAwijZXYU+o/PqdyU+QAHBawM8zAV76pNhPkurgPOZUquExkVX/kQySfiv0EUUxQzqIl48D3RVhv4cvhXD+WXDTYkVERUGO05p7LuoolWI2KO3Gk1nleuTu006XjuqY02aUiYhEKQvV7VO9Jrd7QVK+WNAnovl6QrrxU4WIGYvCvL/7TJbcmOmNLGhX0u8Z7oWrUtOp7VuOZmxtmjz5C+4fjfbFpPsh35god1f9X3NWt5l/djrUk0eU35VgfRl+d01IxcDQEfqLrDs5XtLdWz7OUbfTiegVNet+Vx2AcE00rAZS0Jr9ixA7K/h2lbPMw4LT/iXbH6eGiqFvu/A66WBGyVgdjR4eN+s+ovFk5ECu0JC8M/LXUR6nvWM9VG+TV241KEdN1aXHB5ADEDR+Ida7Zfp/WQMQhJCwA2ydnPiGyQL7ORp8MZo6W0OTsph6ASHUf7YkYNWIv9wykriEmdc7c6got2YAaWBFY/zke7Iltz0+TyAv3shItvUmqw3BABb/x3SD8+t8zL2IWIUgE206YTw1QG4VGxe7kw28qfrWwbOdEE+ndw5e4vcnWOSjUSJEat66K/KD+qaSvvnSM84KaWzUTLGTEolUnHYK7p0O+g67S0BHRF+oT6khHZ//osRvwi0zRqyCaXohxpme62MsUrZnRYaVca2bMbaJBkrjad83xOXmZpKdmImD9FTOsQ==
    MYSQL_ROOT_PASSWORD: AgCWfx514T6yOKGo0mYvre79+bzSynn1tnhmyf6qXWFh5wRGPWZpEY+P7FmxbZrpWwrldiAlIeMdVEGyu13sq+oMWxzafS3VfLj3zT69YDeMOBWXxPzhu0nrbw6GZrNktb+EGewV/J7Rvn/SvnAxEQIOKncKHgw4qkwDdP2MiyoorAtFkiE05VGfupKyoaUuFgOnyopR88ZoIGr9R1FYZxOgW8K28zYIvP+ZCSuSiSKnWDF1N0OUE3fe7Pc9KON0vHXAwUeX4BzBt6fvxqfkkmwVKyPsFVJ84gSLjaWBqclGelivibTLk50BO71zJDOnq872dm/2PmMm4+aVwJn4kFzKHtMKV8m3x5s8nrzcE9XAh/CCEruyQAYAf2L3+itLoqSpQMsSQqcEhA7jOjmrm54EBjcT4pcMktbk0YbTA8vO09ue/KhgfCEJvvtZMZ+ywbxWeldeBmADbL1EguF7rWd23q3Aer2ODkt4noZx5vfRWBQi7WZQldGtlYFpBu+9ndAPwZhdQTpXkNhL7hdhGcYJtcnnY+RyPhm23B1Ffx6VwlHjSmdstGEj0IZNfdzVaB0/ObAHiIVawj/qBA/AcHmO2h3wrgS6t/IKrir7NPKRxvX9i+ezFHGbj7838rKSMH5K7xycMk6z6e6haU4sTHkxjxGhh5qgRpg0ZQ1CdvLgFS6UMNjGV1oDh+5iOiumi1U1m91Sv/1fyvJwRraZGVUV
  template:
    metadata:
      name: pydio-secret
      namespace: pydio
