---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-secret
  namespace: vaultwarden
spec:
  encryptedData:
    ADMIN_TOKEN: AgDGGpDMgmUrIsJ/Hnf/Gpx9JwJ1XZfEfkqW2JSGcrl4hgL9vNlIvo/kIQKQE5nxS5u5tylI/c10SYeotDOz8LMpIOWLyBGlhcrhwO124ea/vUc2FjHqVJJgLVD6VzL1ovbABN05rsPOzMT6nKw6eCffix23Q5FdVZJFDAGFjJTClvzI2+KXtcrWa0YFFiimdnkY5wHv0go0Em0pJ0K0z64k2OPsAOOkb7AQLh8gnxAM3pDbEqHlwxlpKGH8/0JKZRynFX20N8T7WwX/FhONGau/IFpIEgL33YwTyxplvqvQvZOI4e+5Rm9TiuXbjkkHVchh6tidDNSR6DbuIlYYQm2yBbU/VLi2PrNZniz+hLNr9NJfsLblYtpSlr1BJVJ4HOIBd8NhjeKNGO7vcY6dTRVt5RZrcrcI840cqCNXMB9EdYNZsv2F/qmz4Tc8/46UA+9PFluNmQc/Dzxwrih088UFQe8OenLI76I3gesSr5NhPVXd2tStE81+1QhdFh1QKP6vGPV3ewSr/lIrI7N73obK7gb7pbY6rSBG9p2yOolUt8gqf4bKS7MS+XCYO2e5yzXFH7IPVXo/3jgNTfBImj1HDa13T6XxCZ3UnRyeXrsPxo1g3GuK01aWdOTeIour8wjvO+ndrBprSpYQa3PucX4k16msPLYEq3briMapg4YrV8lkDb7u9uR7PD+C+U2HTFOK7ekeP5JIpi4CbNiHkA==
  template:
    metadata:
      name: vaultwarden-secret
      namespace: vaultwarden
