apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-secret
  namespace: vaultwarden
spec:
  encryptedData:
    ADMIN_TOKEN: REPLACE_ME
  template:
    metadata:
      name: vaultwarden-secret
      namespace: vaultwarden
    type: Opaque
