---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rathole-config
  namespace: rathole
spec:
  encryptedData:
    server.toml: AgAI7Y/5hf5Q6gEcoZ3TuPMidqDE6Y77uc8oUFdkCkhSblBRZ5RdYGEUxNnh2KffeQ5NCp58jWJLjqZxMHjCFnhxvbC3oIYToq9KaKTWKlcoZEt+hI4S+BAx+0aWpSrCovgOy/2I369JX/BQVbt26zto847JblzZmmxsio13MklmV/eVKujBq2KeGjpbWkAUtDe8wEOy8yHk+Xb9jnpoLSj04/7uWcwO+bEwAQ2RSUUrqREuBpaHculLEMkvoNqcRswqkNC/LCz3b8MITnO/cC7bxhzEf0a5DnhTMIQeFxO9H1Ab1I1pbnHKvI7r3TUdVWYVVGK/Kj4Zdv80XqQSDERm6YZEtGMfX+8QM4fE0boWaKn5eUKNn8aSnQNGI4RYvk+Jdpbt9bM8V/bs5qzV+sRtIGyieggQBM5XihTCOMWYkKuLTELWnL5OoEzir9YLstMi0ObbtPKQK+cNLaEJknHjluyOEgoApJ7VqNPdnAH9I43vdzN/BGdbHX1MzyWO3gEdG4znj6wASkt+1cuuKIznJf2u/0cUMhlnINAc7lvJS8W0v+G1n3o8iESpSJH43VhoocgHiaSo4EUl12a11gcjCkBSfq8aSLqPwMbcEHgqqACgcA3LNrQHpfXhjUc92fSkeKpXHySCrpZG5IioW/Eq7BCIMBvokgHjUxFz7vUm9wSx2STMP3nWm437KOUHxYr2zTkQQrvyQQ5UQwkOHS1r4zw/p0NTxSMuw2HlB0A8eBqTdihzqSNiOVvWK+Hmc2MKHLL/D695B360IS8iZSbYEQ2gFWRCRa2AAUwD+tlLx8NeAYkiKESe+siO8rCN8zle33otz9PBXyAqGxLwKGojhuXgtA9VTmzzIzC/dCzO0G6B1vrgHDdv4RGq6ROHQqWETkrKXLJAKyVbnpHf380fEPLtiog4Bwyxt751KgW+tNUPIoyN00yKSxH34bWavOJZk9czJh97xp1yJjqn0zXE3LWqZx5mtz2atJhyhlPSR5QlBv7MQ7TT5iCXolae4As57C+Jz6f6NmnIuHj/mYhC
  template:
    metadata:
      name: rathole-config
      namespace: rathole
