---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rathole-config
  namespace: rathole
spec:
  encryptedData:
    server.toml: AgBHWd8jvz/iETbjv1iKxDohyBNYp8D34Y6WT4bsi4486SEs1e/TZsilku4eNgpbx4LG1ErM15EzePnVYZCtmSV7LahNZ0vks34R/4DkONM+NPa4sL4D/GSK/2FyhLyrYXTupc3l70ZObt9P1Zbma1uenEhJkPOlHqtDf+bL4KUiOeOJBVgRp/2NDLadhnyrHywvAzr67wbxnaB1YLwPAJDA0ZtUNkiemaxf44o1FKMSZCjNDR2PnFirJ3U3qYqEYLfHrj80yepjMYHTYG1KLTYkDpAM+0UmhKxzxoitbGV23qQ4emHnJJUYHdlqKw47ATz48HlwBwIlIoj1htUqIoWE4MEAh6q/8rrocD0f3/if6gkxE3RLoJI68JoBKvzfEA7cs7aW7mPcfQS/l2GLihhfzBQaIN/7u76GPAQJ56mziRHXS05uinsQtAYIgcrdjv8cU9jXcqaYsHXCoWc/SX8v67gRdT/ofGmIeZnLmGV1HDZhpJOvSoCsWctfYvoLY0lyjTqtgSERT0nyYd3aYZXU8VAN50W4d/sT4VKYRezvRKSVq67dWkeP7T3BQtJ6iqmqs1dyjc+Q2DKQmCDN/xebavZZAPVw5310sTETmbt3y7KdwvPNURtRqoh8RjhKTL7CVpHDR73I/n3FQBFVsnlrJsZxJJnOuHDTP6UiA/t78c9BLY00JcMMWwSUaamdF5g+EBDC+JMBYUGRvrNXQqK9GpXQeGa7YMDofLtZe6AKoijDE9ez6/whBzGQnWMzdYcN1ljg4bY/8dMeULrbQWsaaHew/tjQop0FPaOv+9ov3rITtsOuwAx3l/Z6ONvFI9qiT8hRMHFvHgJHOUb+kmzW2xnHk6hIurQShtaZvtd0SyCdVxBpHhJEKM51OgPOGOQFE5G/HrcddrFEddie1hKaXjJW2O0WrryCApYGzIJlP6AJgjeFgvDrcP+Yr5Pp/YW/ZGtynQrsBkR1t3iXP9+fR6jM5rGZBY/h094qYcy9Hxn6vclT2GxScmzVIkoNo1mP74l9ED47mbLx6+g5b3GG7h/sCjshbqq5VKlejGaLg6bSLvPvp/uS/1/cZluxBllrwvpuZWOhM8WMv8LpbXn+NKU+3l5yV1K6vyj4uYqP
  template:
    metadata:
      name: rathole-config
      namespace: rathole
