---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: moksori-secret
  namespace: moksori
spec:
  encryptedData:
    DISCORD_TOKEN: AgCD6WQZgJHak2IpKc0GyABAq1dLW3+UiqeXeVzCV4OvQ5NF4Sz8ZxtOWxHJJmCPBkHBcIyi5gsK04E0PgWUGRHFsLDJNamVIvH/FySOR/nYuZONO+tUXHF6QACBMvFYcFpyO/t51AfZlBHRftGGH0HG98O9YLr6jfClnssuGwhtGsGw/1VJgShCbqFMBaRlswG5EMIvj+x+OU/dHn+s7phxDcdZ68f1SV9zh8YxfwXW++j8lc4uWQ3a3w04QfwxKtm3qvCED49utKPWlEvUdntSBj/PzoVxe3kJ0n6CJ2W+RnlOzXxEUTa2eQPaA3QITYH/WaR/z0SAlkNXMsVmo6mZhglZc1ePfNtoYwvnZB+lxVlG97cgPl/+ceAEp7itoCiIvyg0BgK/xgBL4gVIi5JnlZXfK4zTpPUa+y+cxVV5TIC8K5QTwkoAmkdINGQJFXLxrHF1/dcmd6/5yskzjuMxCQxDokou9MEb/6wHnldL6o7gtT9P9St2IZyibbMLaIn87n7jQbXEYZaeOHqr/RUabhENlSMMjRQtlUkFSzJnWlwYuRPoDfU//vDxa6gCPSqdcWfF8jAnXHBY2VSup6cSTy8iootYMDI7pGiv5q4wa/fvPfeDUJd4BEv2Sm3TEYthy/t8+VnXAMPU8AJvIhEnFzZ/z78mdVvBG/QYju+Qr6jLbpe0XFWe+bGF/uiEH0WjfRyuBN1xT4NyITv7dLScBEDnYhCFZpEMLqGhSR6kacB4dfnqaS8JyQT8rwemHRcn+xqq2sk4MzVqiNLh5QFXY4LQdjLg1L0=
  template:
    metadata:
      name: moksori-secret
      namespace: moksori
