apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-seafile
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/wHoIsDReAmer/lab.git
    targetRevision: main
    path: clusters/k3s/apps/seafile
  destination:
    server: https://kubernetes.default.svc
    namespace: seafile
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
