apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-sealed-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default
  source:
    repoURL: https://github.com/wHoIsDReAmer/lab.git
    targetRevision: main
    path: clusters/k3s/infra/sealed-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
