apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ggez-auth
resources:
  - namespace.yml
  - pvc.yml
  - sealedsecret.yml
  - deployment.yml
  - service.yml
  - middleware.yml
  - ingress.yml
