---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ggez-auth-signing-key
  namespace: ggez-auth
spec:
  encryptedData:
    GG_AUTH_SIGNING_KEY: AgCmY1/MrHd5c5XDIS3S0uNzw1EB1K5vQaoJqYRa2nEaroJP9AtOfDNRwFyRnVNFQBevhawM226BeW2MZTT+/tqtSeYjSO3jRRGOi1Vdp1bnHr0N9IvWiSEcUR9uHFUzduvnlAoPqPIe9RJXx2sTn/DsCjs992ZjGGs9eYF486eXaqT51RpLrTMuaEtV7c6rJNc6LRLnqm9quNX4X6hbPnd4YYUHh5CORjQQnMBy39fFuYIK+zLgPUZYuGb/hAoI4Y/Qw7Z0L+lUJ+fcQP4D888jWjIt9wuSxP4OzGzhJ+BE0bq1OK+eoPHDE9Ceqj1GK94K1BiiL1rV6QY1MZxkKoke990k4cZZOWm2OiAYgrkTlAcbmgct69LzqARmzLc3hNa73zID9IiVbhMxrqEnqcvHKGutR5oerjmoDVyt6INndwYdduYDvjD9KkfczhmByuZEOnF9OLmGGSBOw4KG0LV1LCJDU+DGYHpfNFbsB0TnFdZjLG83JGi7cxhhBG+8zK8zzUGJBT3B2rDYhsJAaJlnzzZTRpfM/G0JekJ9GGw7TCNtwt3f2kmFGxsIsbnfYpD4DQbrnP9so1P/BaLseBMOphJAg7B+mvzAV0jFafRf3QOMtPX1e3EaLczEVTlgs1cnCNFvCmOYznNp0qeND8hH6vUb8nm2ZvtW6GQQNB7EVpCGF5SnPzIz0wloPK4WDXqPmb9y0N7stpS42/9GeA+GP1UtOwQCYtxC5XS1o+2KICEIu7LrdGjedz2hSeRye0qYiDQNQOOrsceHOPRHKY1g
  template:
    metadata:
      name: ggez-auth-signing-key
      namespace: ggez-auth
