apiVersion: v1
kind: ConfigMap
metadata:
  name: velocity-config
data:
  velocity.toml: |
    # Velocity Configuration
    config-version = "2.7"

    bind = "0.0.0.0:25577"
    motd = "<#09add3>Minecraft Network"
    show-max-players = 100
    online-mode = true
    force-key-authentication = true
    player-info-forwarding-mode = "modern"

    [servers]
    lobby = "lobby:25565"
    try = ["lobby"]

    [forced-hosts]

    [advanced]
    compression-threshold = 256
    compression-level = -1
    login-ratelimit = 3000
    connection-timeout = 5000
    read-timeout = 30000
    haproxy-protocol = false
    tcp-fast-open = false
    bungee-plugin-message-channel = true
    show-ping-requests = false
    failover-on-unexpected-server-disconnect = true
    announce-proxy-commands = true
    log-command-executions = false
    log-player-connections = true

    [query]
    enabled = false
    port = 25577
    map = "Velocity"

  forwarding.secret: |
    CHANGE_ME_ON_FIRST_BOOT
