---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velocity-forwarding-secret
  namespace: minecraft
spec:
  encryptedData:
    forwarding.secret: AgADAF1ADFRHYg4YcV8KZUYTDC5MnBLSELbPBQsYjb3kNR86KhDMuyIFbQ8yx/H2KLqqGC2DnAv+7rTLoHXvGv4+RPboUaWYzshyVGuMObM91ZlounUKNW/p8yCWoE45AavIWYkcCMxtBzWFqhw5YkLh+6bZw72Fw5ITR9qBGEn1Rk2/Rp/n/Pe4eeiw9ajpILaYdnUoIUHW0CiH+QRbf4HUZaVOXysEunZ0AcBdH3oD3fuqevkYoJA7LR+e5CK+5dG+fV8BU/Ix11NhOKNoNR2LXWPx5JSYgN5uriWWjHhj30v6BGLkw4Y6p+24ZpSAyXTRdl2EZXxIhKQYyIYOdfOpim99IVyhb6AnmyWf0t4qeRSFdlDBE+lU/0Yda2tCp79bBGzQAtSlPAOB04JolQMCgwgQS5IFM5g+4DQbEyYZHKH7CbuKx+cD5m1/SkNvaYsdGqRRS9mb5V/vS9dahrTOAk6/cfqvqM92ZySuAj3Q3dNqgFjuCfKsDnwap305KT33HtD0foWYKvKWgFK9zNfGb4P8QU7OVeV4gpCPTqxLrrAmTJnX+yeE7pG1O4Zx4d0DNmUq1Nm9bpU+SgxOoRNSIDFNPe0UADPf9pRzXQ/jvMhzDw91kPxMDghN60U+kbQdBTNUXSdXLlkVLJo31x4mTBxPsA7HONxeW0VNSSdE1YQUeXhQ3q6vuXZ35RWYKj/bLl9BQY41/Nt47RFTg7NzJ41A5og7ysIP11mYK+Jrmab97pfAF4MdyAup+g==
  template:
    metadata:
      name: velocity-forwarding-secret
      namespace: minecraft
