---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sish-hostkey
  namespace: sish
spec:
  encryptedData:
    ssh_host_ed25519_key: AgBX+4+jZPkFPDjlJmFs6yTGtOgFDhwm5GEhzu7XJs56n9YHt8KDLuMvPdQ+RJb7u6V+uR4OZ5AU4ljgLxrQ0ndwk6sJyrPIcDvqH+tH70hZGJWUK2jz87Gkol5B/V9h09njrumfhH66a8XIOeACxR/bFQ75557Nl5bAIeTr5OAUC6zwdsWJvdZW9bC8Bc/ok1Yb/UoIFWNdhMUKZ1iQI8UX+K9bB52tfWmg8mFz8mGL/SBRJRub0UWqfr0BBIk0Si6C//ESBB3ffjTml1sU6ovwBpL+n7nHgdgh+oXkZ5SNpZ19BfSnc1++kZJ9iakhs+mtZK/7NnyJx2ufxjUDD8hDUUWIkQjxqNDzfOXWD1ipDVBc2CJVa32cr9pN92AXb9UYjoBsUkNPTWmiYR9P84o7kQ/FDUimxow/PpAxG7hMRltJCLv6N6ybGO8U41jbnKbpXpzRTc4aB9W7hlT7uSUJFPrZiqeYGqOd1xzb1hNz7s7CfAS/CNkGVPbmKVV7nbgrJJMMoqfXvY6St/drPwQ7ewXIdctyV+CKOkCWquj6ZR7iqEZDc44RUj0PvHxy3JsgLM+50TUeAtNc4euz0qkNGQ6U6tHjLEy5tp3Q3lhr2hno7rjUw5yTdg3ZY+TQ+aYxlmUhT4w4/8GJezjIbO2kCf6KK7axPke8Ilw9inhiHEP2/jtHXt+IjVKq13kOTHrG6dudT178ahXT8M+jTf/7YUTWxocYSQjBpn56h8DXpgxZLZv2ttT5ADKXYKK6HBF3fAK8jZCF/1bolCfBLr8QvlUbX95TzHLeJuY35bCBp/V/4QwXf6vV4R6ge4ALeOhENB0IYphFneMOkh27UwFUPFg5PFt3mgutsVs/FFPYgRpoqUux/f/CXv016ahwZs8/OiYZOgaQpI0i4LV9+2ycK0ieG3/+Umun7nnhWpe+2NxgWNqiUuPAngPjG36ydpvtR4kIfrbk+Yyw16lizkl7rNuP5hRdTUIMSDmyeBCMEFDO8CMCVYU66tfQzzsembqKsDfZ7qF6hFwDKXX9XGG2LG7BDnDLLW5TWoHpLCS30yVSh7OcZljmEIl9bftwlEkRKsd9HTuK+O2mfOT3VxFQgdWVATwKGYEnhYpTANcZMef3N2Srxz4mrzOySwPNh7fzx3dTWV8MQszmK9q+UozgysvYAsC9YPxsiBxJwye0UZlcx65FX5ZoigflccVkGXocn0JKN6RiJJm0Yfb7MaA=
  template:
    metadata:
      name: sish-hostkey
      namespace: sish
